import {SUPPLIERS} from "./suppliers.js";

const IMPORTANT_SUPPLIERS = [
    SUPPLIERS.Tourvis,
    SUPPLIERS.Privia,
    SUPPLIERS.Naver
]
const SUPPLIERS_WITH_DETAIL_PRICE = [
    SUPPLIERS.Privia,
    SUPPLIERS.Tourvis,
]
const MAX_RANK_WITH_DETAIL_PRICE = 20

export {IMPORTANT_SUPPLIERS, SUPPLIERS_WITH_DETAIL_PRICE, MAX_RANK_WITH_DETAIL_PRICE}