import {SUPPLIERS} from "./suppliers.js";

const IMPORTANT_SUPPLIERS = [
    SUPPLIERS.Tourvis,
    SUPPLIERS.Privia,
    SUPPLIERS.Naver
]
const SUPPLIERS_WITH_DETAIL_PRICE = [
    SUPPLIERS.Privia,
    SUPPLIERS.Tourvis,
]
const MAX_RANK_WITH_DETAIL_PRICE = 20

const DAY_OF_WEEKS_CONDITION = [1, 6];
const SUBSEQUENT_WEEKS_CONDITION = [3, 5];

export {
    IMPORTANT_SUPPLIERS,
    DAY_OF_WEEKS_CONDITION,
    SUBSEQUENT_WEEKS_CONDITION,
    SUPPLIERS_WITH_DETAIL_PRICE,
    MAX_RANK_WITH_DETAIL_PRICE
}